name: Package Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php: 8.1
          coverage: true
          extensions: json, mbstring
        env:
          fail-fast: true

      - name: Validate composer setup
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php-8.1-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-8.1-${{ hashFiles('**/composer.json') }}"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Normalize composer file
        run: composer normalize --dry-run

      - name: Run test suite
        run: vendor/bin/phpunit -v

      - name: Run static code analysis
        run: vendor/bin/phpstan --memory-limit=-1

      - name: Upload coverage results
        uses: codecov/codecov-action@v1
